name: Add sponsors to README
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0

jobs:
  update-readme-with-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ’– Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          organization: true
          token: ${{ secrets.ADD_SPONSORS_TO_README }}
